apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-onsite-arrangement
spec:
  selector:
    matchLabels:
      app: sf-onsite-arrangement
  replicas: 1
  template:
    metadata:
      labels:
        app: sf-onsite-arrangement
    spec:
      volumes:
        - name: config-vhost-volume
          configMap:
            name: myvhost-configmap
        - name: config-start-script
          configMap:
            name: myscript-configmap
        - name: sf-onsite-arrangement-src
          persistentVolumeClaim:
            claimName: sf-onsite-arrangement-src
      containers:
      - name: sf-onsite-arrangement
        image: registry-dkr.pvcp.intra:5000/pvcp/httpd:php-74-v20201215
        volumeMounts:
        - mountPath: /etc/httpd/vhosts.d
          name: config-vhost-volume

      initContainers:
      - command:
        - /bin/sh
        - /tmp/script/start.sh
        image: registry-dkr.pvcp.intra:5000/pda/sf-onsite-arrangement:develop-d6001185
        imagePullPolicy: Always
        name: src-sf-onsite-arrangement
#      volumes:
#      - name: sf-onsite-arrangement-src
#        persistentVolumeClaim:
#          claimName: sf-onsite-arrangement-src
#      - configMap:
#          defaultMode: 511
#          name: sf-onsite-arrangement-start
#          optional: false
#        name: startup
#        volumeMounts:
#        - mountPath: /tmp/data
#          name: sf-onsite-arrangement-src
#        - mountPath: /tmp/script
#          name: startup
