apiVersion: v1
data:
  config.json: |
    <VirtualHost *:80>
    ServerName sf-onsite-arrangement
    ServerAlias sf-onsite-arrangement.pierreetvacances.com
    DocumentRoot /var/www/sf-onsite-arrangement/public
    
    # Crossdomain
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET,POST,OPTIONS,DELETE,PUT"
    Header set Access-Control-Allow-Headers "X-Accept-Charset,X-Accept,Content-Type,Authorization,Cache-Control,X-Http-Method-Override"

    <Directory /var/www/sf-onsite-arrangement/public>
    AllowOverride None
    Require all granted

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /index.php [QSA,L]

    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
    RewriteRule .* - [F]
    </Directory>
    CustomLog "|/usr/local/etc/httpd/bin/rotatelogs -n 3 /var/log/httpd/sf-onsite-arrangement.access_log 86400" combined
    ErrorLog /dev/stderr
    </VirtualHost>
  
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: u-wf5pt2z7o4
  creationTimestamp: "2021-09-06T15:27:53Z"
  labels:
    cattle.io/creator: norman
    source: github
  name: myvhost-configmap

