apiVersion: v1
data:
  start.sh: "cp -r /var/www/sf-onsite-arrangement /tmp/data"
  
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: u-wf5pt2z7o4
  creationTimestamp: "2021-09-06T15:27:53Z"
  labels:
    cattle.io/creator: norman
  name: myscript-configmap
