apiVersion: v1
kind: Service
metadata: 
  name: sf-onsite-arrangement
  labels:
    app: sf-onsite-arrangement
    environment: dev
spec: 
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      name: sf-onsite-arrangement-port
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: sf-onsite-arrangement
    environment: dev
