apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: go-onsite-alert
        image: registry-dkr.pvcp.intra:5000/pda/go-onsite-alert:develop-10daf607
        imagePullPolicy: Always
        resources:
          requests:{}
        volumeMounts:
        - mountPath: /go/config
          name: config
        - configMap:
           name: myconfig-map2
	  name: config
