apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-onsite-alerte
spec:
  selector:
    matchLabels:
      app: onsite-alerte
  replicas: 2
  template:
    metadata:
      labels:
        app: onsite-alerte
    spec:
      volumes:
        - name: config-data-volume
          configMap:
            name: my-clone-config
      containers:
      - name: go-onsite-alert
        image: registry-dkr.pvcp.intra:5000/pda/go-onsite-alert:develop-10daf607
        volumeMounts:
        - mountPath: /go/config/
          name: config-data-volume
